version: "2"
plugins:
  csslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      fallback-colors:
        enabled: false
      argument-count:
        enabled: false
      complex-logic:
        enabled: false
      file-lines:
        enabled: false
      method-complexity:
        enabled: false
      method-count:
        enabled: false
      method-lines:
        enabled: false
      nested-control-flow:
        enabled: false
      return-statements:
        enabled: true
      similar-code:
        enabled: false
      identical-code:
        enabled: true
      duplication:
        enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_patterns:
  - "css/bootstrap*.*"
  - "js/bootstrap*.*"
  - "fonts/fontello.css*
